name: Tests in Ubuntu
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cabal
        run: |
          sudo apt-get install cabal-install make
          cabal update
      - name: Install Idris by Cabal
        run: |
          cabal install idris
      - name: Run tests
        run: |
          idris --testpkg ether-momonga.ipkg
